services:
  - type: web
    name: invitation-platforma
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 180 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_PUBLIC_URL
        value: https://invitation-platforma.onrender.com
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: FLASK_ENV
        value: production